# -*- coding: utf-8 -*-
"""test2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R3C1PIla3cOJwmFj0L4SgTsGNv37Jre-
"""


import pandas as pd

df = pd.read_json("data/resumes_dataset.jsonl", lines=True)
df.head()

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

vectorizer = TfidfVectorizer(max_features=5000)
X = vectorizer.fit_transform(df['Text'])

model = LogisticRegression(max_iter=1000)
model.fit(X, df['Category'])

print("Role model trained ✅")

def label_line(line):
    lower = line.lower()

    if any(w in lower for w in ["developed","built","created","designed","implemented"]):
        return "DESCRIPTION"
    elif len(line.split()) <= 6 and not line.endswith('.'):
        return "TITLE"
    elif any(w in lower for w in ["java","python","sql","react","node"]):
        return "SKILLS"
    else:
        return "OTHER"

lines = []
for text in df['Text']:
    for line in text.split('\n'):
        line = line.strip()
        if len(line) > 3:
            lines.append(line)

labels = [label_line(line) for line in lines]

vectorizer_lines = TfidfVectorizer(max_features=3000)
X_lines = vectorizer_lines.fit_transform(lines)

model_lines = LogisticRegression(max_iter=1000)
model_lines.fit(X_lines, labels)

import re

def extract_projects(text):

    lines = [l.strip() for l in text.split('\n') if l.strip()]

    X = vectorizer_lines.transform(lines)
    preds = model_lines.predict(X)

    projects = []
    current_project = None
    in_project_section = False

    for line, label in zip(lines, preds):

        clean = re.sub(r'\s+', ' ', line)
        lower = clean.lower()

        # 🔥 detect project section (robust)
        if "project" in lower:
            in_project_section = True

        # 🔥 stop at major sections
        if any(x in lower for x in ["education", "technical skills", "skills"]):
            in_project_section = False

        # ❌ skip if not in project section
        if not in_project_section:
            continue

        # 🔥 FIX: REMOVE "projects" word from line
        clean = re.sub(r'(?i)projects?', '', clean).strip()
        lower = clean.lower()

        # 🔥 TITLE DETECTION (RELAXED)
        if (
            label == "TITLE" and
            2 <= len(clean.split()) <= 8 and
            not clean.endswith('.') and
            not clean.isupper() and
            not any(x in lower for x in [
                "email", "phone", "linkedin", "github"
            ])
        ):
            current_project = {
                "project_name": clean,
                "summary": ""
            }
            projects.append(current_project)
            continue

        # 🔥 DESCRIPTION
        if current_project:
            if len(clean.split()) > 5:
                current_project["summary"] += " " + clean

    # 🔥 CLEAN OUTPUT
    final = []
    for p in projects:
        if len(p["summary"].split()) > 5:
            final.append({
                "project_name": p["project_name"],
                "summary": " ".join(p["summary"].split()[:25]) + "..."
            })

    return final[:5]

df.columns

df['combined'] = (
    df['Text'].fillna('') + " " +
    df['Skills'].fillna('') + " " +
    df['Experience'].fillna('') + " " +
    df['Education'].fillna('')
)

import re

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'\n', ' ', text)
    text = re.sub(r'[^a-zA-Z0-9 ]', '', text)
    return text

df['cleaned'] = df['combined'].apply(clean_text)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['role_encoded'] = le.fit_transform(df['Category'])

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=7000)  # increased power
X = vectorizer.fit_transform(df['cleaned'])
y = df['role_encoded']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = LogisticRegression(max_iter=1200)
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

def adjust_roles_soft(skills, roles):

    skills = [s.lower() for s in skills]
    role_dict = dict(roles)

    # 🔥 SIMPLE CONDITION (no complex logic)
    if "react" in skills and "node" in skills:
        role_dict["Full Stack Developer"] = role_dict.get("Full Stack Developer", 0) + 0.6

    if "python" in skills:
        role_dict["Python Developer"] = role_dict.get("Python Developer", 0) + 0.3

    if "java" in skills:
        role_dict["Java Developer"] = role_dict.get("Java Developer", 0) + 0.3

    if "scikit-learn" in skills:
        role_dict["Data Science"] = role_dict.get("Data Science", 0) + 0.3

    total = sum(role_dict.values())
    role_dict = {k: v / total for k, v in role_dict.items()}

    return sorted(role_dict.items(), key=lambda x: x[1], reverse=True)[:3]

def predict_roles(text):
    cleaned = clean_text(text)
    vec = vectorizer.transform([cleaned])

    probs = model.predict_proba(vec)[0]

    top_roles = sorted(
        zip(le.classes_, probs),
        key=lambda x: x[1],
        reverse=True
    )[:3]

    # Normalize confidence (optional)
    total = sum([p for _, p in top_roles])
    top_roles = [(r, float(p/total)) for r, p in top_roles]

    return top_roles

def extract_skills(text):
    skills_db = [

        "python", "java", "c", "c++", "c#", "javascript", "typescript",

        "html", "css", "react", "angular", "vue", "bootstrap", "tailwind",

        "node", "nodejs", "express", "spring", "spring boot",
        "django", "flask", "hibernate", "jdbc",

        "sql", "mysql", "postgresql", "mongodb", "oracle", "sqlite",

        "aws", "azure", "gcp", "docker", "kubernetes", "git", "github",

        "scikit-learn",
        "machine learning", "deep learning",

        "linux", "unix", "windows"
    ]

    return [skill for skill in skills_db if skill in text.lower()]

def calculate_score(skills, projects, text):
    score = 0

    score += min(len(skills) * 4, 30)
    score += min(len(projects) * 10, 30)

    if "experience" in text.lower():
        score += 20

    if any(word in text.lower() for word in ["btech", "mca", "degree"]):
        score += 10

    return min(score, 100)

print(model.classes_)

def extract_soft_skills(text):

    soft_skills_db = [
        "communication", "leadership", "teamwork", "collaboration",
        "problem solving", "critical thinking", "adaptability",
        "time management", "creativity", "decision making",
        "analytical thinking", "interpersonal skills"
    ]

    text = text.lower()

    return [skill for skill in soft_skills_db if skill in text]


def detect_soft_skills_from_actions(text):

    text = text.lower()

    mapping = {
        "lead": "leadership",
        "managed": "leadership",
        "team": "teamwork",
        "collaborated": "teamwork",
        "worked with": "teamwork",
        "solved": "problem solving",
        "improved": "analytical thinking",
        "organized": "management",
        "communicated": "communication"
    }

    found = set()

    for word, skill in mapping.items():
        if word in text:
            found.add(skill)

    return list(found)


def extract_all_soft_skills(text):

    direct = extract_soft_skills(text)
    inferred = detect_soft_skills_from_actions(text)

    return list(set(direct + inferred))

import pdfplumber

def extract_text_from_pdf(file):
    text = ""

    with pdfplumber.open(file) as pdf:
        for page in pdf.pages:

            # 🔥 preserve layout (THIS IS KEY)
            t = page.extract_text(x_tolerance=2, y_tolerance=2)

            if t:
                text += t + "\n"

    return text





# pdf_file = "web_development_resume.pdf"

# text = extract_text_from_pdf(pdf_file)

# skills = extract_skills(text)

# # 🔥 NEW LINE
# soft_skills = extract_all_soft_skills(text)

# roles = predict_roles(text)
# roles = adjust_roles_soft(skills, roles)

# projects = extract_projects(text)

# score = calculate_score(skills, projects, text)

# print("Top Roles:", roles)
# print("Skills:", skills)
# print("Soft Skills:", soft_skills)   # ✅ NEW OUTPUT
# print("Projects:", projects)
# print("Score:", score)

# print(model.classes_)

import pickle

pickle.dump(model, open("model.pkl", "wb"))
pickle.dump(vectorizer, open("vectorizer.pkl", "wb"))
pickle.dump(le, open("label_encoder.pkl", "wb"))
pickle.dump(model_lines, open("model_lines.pkl", "wb"))
pickle.dump(vectorizer_lines, open("vectorizer_lines.pkl", "wb"))

print("✅ Models saved successfully")