# -*- coding: utf-8 -*-
"""test2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R3C1PIla3cOJwmFj0L4SgTsGNv37Jre-
"""


import pandas as pd

df = pd.read_json("data/resumes_dataset.jsonl", lines=True)
df.head()

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

vectorizer = TfidfVectorizer(max_features=5000)
X = vectorizer.fit_transform(df['Text'])

model = LogisticRegression(max_iter=1000)
model.fit(X, df['Category'])

print("Role model trained ✅")


df.columns

df['combined'] = (
    df['Text'].fillna('') + " " +
    df['Skills'].fillna('') + " " +
    df['Experience'].fillna('') + " " +
    df['Education'].fillna('')
)

import re

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'\n', ' ', text)
    text = re.sub(r'[^a-zA-Z0-9 ]', '', text)
    return text

df['cleaned'] = df['combined'].apply(clean_text)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['role_encoded'] = le.fit_transform(df['Category'])

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=7000)  # increased power
X = vectorizer.fit_transform(df['cleaned'])
y = df['role_encoded']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = LogisticRegression(max_iter=1200)
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

def adjust_roles_soft(skills, roles):

    skills = [s.lower() for s in skills]
    role_dict = dict(roles)

    # 🔥 SIMPLE CONDITION (no complex logic)
    if "react" in skills and "node" in skills:
        role_dict["Full Stack Developer"] = role_dict.get("Full Stack Developer", 0) + 0.6

    if "python" in skills:
        role_dict["Python Developer"] = role_dict.get("Python Developer", 0) + 0.3

    if "java" in skills:
        role_dict["Java Developer"] = role_dict.get("Java Developer", 0) + 0.3

    if "scikit-learn" in skills:
        role_dict["Data Science"] = role_dict.get("Data Science", 0) + 0.3

    total = sum(role_dict.values())
    role_dict = {k: v / total for k, v in role_dict.items()}

    return sorted(role_dict.items(), key=lambda x: x[1], reverse=True)[:3]

def predict_roles(text):
    cleaned = clean_text(text)
    vec = vectorizer.transform([cleaned])

    probs = model.predict_proba(vec)[0]

    top_roles = sorted(
        zip(le.classes_, probs),
        key=lambda x: x[1],
        reverse=True
    )[:3]

    # Normalize confidence (optional)
    total = sum([p for _, p in top_roles])
    top_roles = [(r, float(p/total)) for r, p in top_roles]

    return top_roles

TECHNICAL_SKILLS = {

    "Languages": [
        "python", "java", "c", "c++", "c#", "javascript",
        "typescript", "go", "golang", "rust", "php",
        "kotlin", "swift", "r"
    ],

    "Frontend": [
        "html", "css", "react", "react native",
        "angular", "vue", "next.js", "nextjs",
        "tailwind", "tailwind css",
        "bootstrap", "redux", "jquery"
    ],

    "Backend": [
        "node", 
        "express", 
        "nestjs",
        "django",
        "flask",
        "fastapi",
        "spring",
        "spring boot",
        "hibernate",
        "jdbc",
        "rest api",
        "graphql",
        "socket.io",
        "jwt"
    ],

    "Database": [
        "sql",
        "mysql",
        "postgresql",
        "mongodb",
        "oracle",
        "sqlite",
        "redis",
        "firebase",
        "supabase",
        "mongoose"
    ],

    "Cloud": [
        "aws",
        "azure",
        "gcp",
        "docker",
        "kubernetes",
        "jenkins",
        "github actions",
        "vercel",
        "netlify"
    ],

    "AI": [
        "machine learning",
        "deep learning",
        "tensorflow",
        "keras",
        "pytorch",
        "scikit-learn",
        "opencv",
        "pandas",
        "numpy",
        "matplotlib",
        "seaborn",
        "langchain",
        "huggingface",
        "transformers"
    ],

    "Tools": [
        "git",
        "github",
        "gitlab",
        "postman",
        "figma",
        "linux",
        "jira",
        "vscode",
        "intellij",
        "eclipse"
    ]
}


def extract_skills(text):

    text=text.lower()

    result={}
    all_skills=[]

    for category,skills in TECHNICAL_SKILLS.items():

        found=[]

        for skill in skills:

            pattern=r"\b"+re.escape(skill.lower())+r"\b"

            if re.search(pattern,text):

                found.append(skill)
                all_skills.append(skill)

        result[category]=sorted(found)

    return {
        "categorized":result,
        "all":sorted(set(all_skills))
    }

def calculate_score(skills, text):

    if isinstance(skills, dict):
        skills = skills["all"]

    score = 0
    lower = text.lower()

    # Technical Skills (40)
    score += min(len(skills) * 3, 40)

    # Education (15)
    if any(x in lower for x in [
        "btech",
        "bachelor",
        "mca",
        "master",
        "degree"
    ]):
        score += 15

    # Experience (20)
    if "present" in lower or "experience" in lower:
        score += 20

    # Projects (15)
    if any(x in lower for x in [
        "project",
        "developed",
        "built",
        "created"
    ]):
        score += 15

    # Contact (10)
    if re.search(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}", text):
        score += 5

    if re.search(r"\+?\d[\d\s\-]{8,15}", text):
        score += 5

    return min(score, 100)

def extract_contact_info(text):

    email = re.search(
        r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}",
        text
    )

    phone = re.search(
        r"\+?\d[\d\s\-]{8,15}",
        text
    )

    linkedin = re.search(
        r"https?://(?:www\.)?linkedin\.com/[^\s]+",
        text,
        re.I
    )

    github = re.search(
        r"https?://(?:www\.)?github\.com/[^\s]+",
        text,
        re.I
    )

    return {
        "email": email.group(0) if email else "Not Found",
        "phone": phone.group(0) if phone else "Not Found",
        "linkedin": linkedin.group(0) if linkedin else "Not Found",
        "github": github.group(0) if github else "Not Found"
    }

def extract_education(text):

    degrees=[]

    lower=text.lower()

    for degree in [
        "btech",
        "mca",
        "bachelor",
        "master",
        "bsc",
        "msc"
    ]:

        if degree in lower:

            degrees.append(degree.upper())

    return degrees


def extract_experience(text):
    lower = text.lower()

    if "present" in lower:
        return "Experienced"

    match = re.search(
        r"\d+\+?\s*(years?|months?)",
        lower
    )
    if match:
        return match.group()

    ranges = re.findall(
        r"(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\s+\d{4}",
        lower
    )

    if ranges:
        return f"{len(ranges)} work period(s) found"

    if "fresher" in lower:
        return "Fresher"

    return "Not Mentioned"

print(model.classes_)

ACTION_MAPPING={

    "led":"Leadership",
    "managed":"Leadership",

    "collaborated":"Teamwork",
    "worked with":"Teamwork",

    "implemented":"Problem Solving",
    "developed":"Problem Solving",
    "built":"Problem Solving",

    "optimized":"Analytical Thinking",
    "improved":"Analytical Thinking",

    "designed":"Creativity",

    "communicated":"Communication",
    "presented":"Communication"
}

DIRECT_SOFT_SKILLS=[
    "communication",
    "leadership",
    "teamwork",
    "problem solving",
    "critical thinking",
    "adaptability",
    "time management",
    "creativity",
    "analytical thinking"
]


def extract_all_soft_skills(text):

    lower=text.lower()

    found=set()

    for skill in DIRECT_SOFT_SKILLS:

        if skill in lower:

            found.add(skill.title())

    for word,skill in ACTION_MAPPING.items():

        if word in lower:

            found.add(skill)

    return sorted(found)

import pdfplumber

def extract_text_from_pdf(file):
    text = ""

    with pdfplumber.open(file) as pdf:
        for page in pdf.pages:

            # 🔥 preserve layout (THIS IS KEY)
            t = page.extract_text(x_tolerance=2, y_tolerance=2)

            if t:
                text += t + "\n"

    return text





pdf_file = "Mohit_Soni_resume_nitkkr(1).pdf"

text = extract_text_from_pdf(pdf_file)

skills = extract_skills(text)

soft_skills = extract_all_soft_skills(text)

education = extract_education(text)

experience = extract_experience(text)

contact = extract_contact_info(text)

roles = predict_roles(text)
roles = adjust_roles_soft(skills["all"], roles)

score = calculate_score(skills, text)

print("Roles:", roles)
print("Skills:", skills)
print("Soft Skills:", soft_skills)
print("Education:", education)
print("Experience:", experience)
print("Contact:", contact)
print("Score:", score)

import pickle

pickle.dump(model, open("model.pkl", "wb"))
pickle.dump(vectorizer, open("vectorizer.pkl", "wb"))
pickle.dump(le, open("label_encoder.pkl", "wb"))


print("✅ Models saved successfully")